{
 "title": "LOGS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(container_fs_limit_bytes,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Логи по сервисам", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🔍 Последние логи Spring-Boot",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{container=~\"/$container\"}"
    }
   ]
  },
  {
   "title": "📊 Количество логов по времени",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({container!=\"\"}[1m])",
     "legendFormat": "{{container}} - {{level}}"
    }
   ]
  },
  {
   "title": "📊 BAD ROWS (ERROR|Exception|fail|WARN)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container=~\".+\",container!=\"/loki\",container!=\"/gpts-infra-dev-grafana-1\"}[1m] |~ \"ERROR|Exception|fail|WARN\")) by (container)",
     "legendFormat": "BAD ROWS {{container}}"
    }
   ]
  },
  {
   "title": "Логи GPTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "🔍 Последние логи",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container!=\"/loki\",container!=\"\",level=\"\"}"
      }
     ]
    },
    {
     "title": "🔍 Последние логи (WARN|ERROR)",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "direction": "backward",
       "expr": "{container!=\"\",level=~\"WARN|ERROR\"}"
      }
     ]
    },
    {
     "title": "⚠️ Ошибки (фильтр по словам)",
     "type": "logs",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{container=~\".+\",container!=\"/loki\",container!=\"/gpts-infra-dev-grafana-1\"} |~ \"ERROR|Exception|fail|WARN\"",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "🔍 Последние логи Spring-Boot",
     "type": "logs",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "direction": "forward",
       "expr": "{container!=\"/loki\",container!=\"\",container!~\"/gpts-infra.*\",container!=\"/cadvisor\",container!=\"/grafana-agent\"}"
      }
     ]
    }
   ]
  }
 ]
}