{
 "title": "TS",
 "tags": [
  "app",
  "workers",
  "api",
  "orchestrator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "GLOBAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "up", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "increase(http_server_requests_seconds_count{handler!=\"/metrics\", handler!=\"/healthz\", uri!~\"/actuator/.*\"}[1m])",
       "legendFormat": "HTTP {{uri}} - {{method}} - {{status}} - {{job}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{handler!=\"/metrics\", handler!=\"/healthz\", uri!~\"/actuator/.*\"}[1m])",
       "legendFormat": "HTTP {{uri}} - {{method}} - {{status}} - {{job}}"
      }
     ]
    },
    {
     "title": "http_requests_total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 11, "y": 16 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{handler!=\"/metrics\", handler!=\"/healthz\", uri!~\"/actuator/.*\"}[1m]))",
       "legendFormat": "HTTP {{uri}} - {{method}} - {{status}} - {{job}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "logback_events_total{level!~\"debug|info|trace\"}",
       "legendFormat": "{{job}}: {{level}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(hikaricp_connections_active)",
       "legendFormat": "hikaricp_connections_active"
      },
      { "expr": "sum(hikaricp_connections_max)", "legendFormat": "hikaricp_connections_max" },
      {
       "expr": "sum(hikaricp_connections_pending)",
       "legendFormat": "hikaricp_connections_pending"
      },
      { "expr": "sum(hikaricp_connections_idle)", "legendFormat": "hikaricp_connections_idle" }
     ]
    }
   ]
  },
  {
   "title": "gpts-clients-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-clients-service\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-clients-service\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-clients-service\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{pool=\"GPTS-clients-HikariPool\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{pool=\"GPTS-clients-HikariPool\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{pool=\"GPTS-clients-HikariPool\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{pool=\"GPTS-clients-HikariPool\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 154 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{job=\"gpts-clients-service\",uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Максимальное время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 154 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{job=\"gpts-clients-service\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 154 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-clients-service\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-unit-core",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12144 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-unit-core\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12144 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-unit-core\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-unit-core\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12144 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-unit-core\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-unit-core\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-unit-core\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-unit-core\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12152 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-unit-core\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-unit-open",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18519 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-unit-open\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18519 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-unit-open\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-unit-open\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18519 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-unit-open\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-unit-open\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-unit-open\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-unit-open\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "Приклад",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18527 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "open_unit_success_total{application=\"gpts-unit-open\"}",
       "legendFormat": "open_unit_success_total"
      },
      {
       "expr": "open_unit_success_total{application=\"gpts-unit-open\"}",
       "legendFormat": "open_unit_success_total"
      },
      {
       "expr": "open_unit_failed_total{application=\"gpts-unit-open\"}",
       "legendFormat": "open_unit_failed_total"
      }
     ]
    },
    {
     "title": "Внешние вызовы",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18527 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "external_call_duration_seconds_count{application=\"gpts-unit-open\"}",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18527 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-unit-open\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-unit-close",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23762 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-unit-close\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23762 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-unit-close\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-unit-close\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23762 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-unit-close\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-unit-close\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-unit-close\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-unit-close\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "Внешние вызовы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23770 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gpts_unit_close_requests_total", "legendFormat": "open_unit_success_total" },
      {
       "expr": "gpts_unit_close_processed_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Внешние вызовы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23770 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "gpts_unit_close_external_call_total{job=\"gpts-unit-close\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23770 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-unit-close\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-transfer-resolver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-transfer-resolver\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-transfer-resolver\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-transfer-resolver\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 49 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-transfer-resolver\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Внешние вызовы",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "transfer_resolver_user_service_calls_total",
       "legendFormat": "Количество вызовов сервиса пользователей"
      },
      {
       "expr": "transfer_resolver_user_service_errors_total",
       "legendFormat": "Количество ошибок при вызове сервиса пользователей"
      },
      {
       "expr": "transfer_resolver_account_service_calls_total",
       "legendFormat": "Количество вызовов сервиса счетов"
      },
      {
       "expr": "transfer_resolver_account_service_errors_total",
       "legendFormat": "Количество ошибок при вызове сервиса счетов"
      },
      {
       "expr": "transfer_resolver_transfer_service_calls_total",
       "legendFormat": "Количество вызовов сервиса переводов"
      },
      {
       "expr": "transfer_resolver_transfer_service_errors_total",
       "legendFormat": "Количество ошибок при вызове сервиса переводов"
      }
     ]
    },
    {
     "title": "Статистика резолвера",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "transfer_resolver_enrich_requests_total",
       "legendFormat": "Количество успешных обогащений переводов"
      },
      {
       "expr": "transfer_resolver_enrich_success_total",
       "legendFormat": "Количество успешных обогащений переводов"
      },
      {
       "expr": "transfer_resolver_enrich_errors_total",
       "legendFormat": "__auto"
      },
      {
       "expr": "transfer_resolver_enrich_not_found_total",
       "legendFormat": "Количество случаев, когда пользователь или счет не найдены"
      }
     ]
    },
    {
     "title": "Максимальное время обработки",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "transfer_resolver_enrich_request_duration_seconds_max",
       "legendFormat": "transfer_resolver_enrich_request_duration_seconds_max"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-transfer-orchestrator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-transfer-orchestrator\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-transfer-orchestrator\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-transfer-orchestrator\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-transfer-orchestrator\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-transfer-orchestrator\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-transfer-orchestrator\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-transfer-orchestrator\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "Общая статистика переводов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "targets": [
      { "expr": "transfer_completed_total", "legendFormat": "{{status}}" },
      { "expr": "transfer_failed_total", "legendFormat": "{{status}}" },
      { "expr": "transfer_rollbacked_total", "legendFormat": "{{status}}" }
     ]
    },
    {
     "title": "Максимальное время обработки",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{job=\"gpts-transfer-orchestrator\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "transfer_resolver_enrich_request_duration_seconds_max"
      }
     ]
    },
    {
     "title": "Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "targets": [
      {
       "expr": "spring_kafka_template_seconds_count{job=\"gpts-transfer-orchestrator\"}",
       "legendFormat": "{{name}} - {{result}}"
      }
     ]
    },
    {
     "title": "gRPC вызовов по сервисам",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "targets": [
      { "expr": "grpc_calls_total", "legendFormat": "всего вызовов {{service}}" },
      {
       "expr": "grpc_calls_failed_total",
       "legendFormat": "всего вызовов с ошибкой {{service}}"
      }
     ]
    },
    {
     "title": "Сага шаги",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "targets": [
      { "expr": "saga_steps_completed_total", "legendFormat": "Complited step: {{step}}" },
      { "expr": "saga_steps_failed_total", "legendFormat": "Failed step: {{step}}" }
     ]
    },
    {
     "title": "Ретраи",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 16, "y": 23 },
     "targets": [
      { "expr": "transfer_retry_total", "legendFormat": "{{status}}" }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 4, "x": 20, "y": 23 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-transfer-orchestrator\"}",
       "legendFormat": "{{level}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-transfer-operation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc вызовы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
     "targets": [
      {
       "expr": "grpc_server_call_duration_seconds_count{application=\"gpts-transfer-operation\"}",
       "legendFormat": "{{grpc_method}} - {{grpc_status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 168 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-transfer-operation\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-transfer-operation\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-transfer-operation\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-transfer-operation\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 168 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-transfer-operation\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "grpc_server_processing_duration_seconds_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
     "targets": [
      {
       "expr": "grpc_server_processing_duration_seconds_max{application=\"gpts-transfer-operation\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Kafka Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
     "targets": [
      {
       "expr": "spring_kafka_template_seconds_count{application=\"gpts-transfer-operation\"}",
       "legendFormat": "{{result}}"
      }
     ]
    },
    {
     "title": "Fee stats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
     "targets": [
      {
       "expr": "commission_fee_processed_total",
       "legendFormat": "общее количество обработанных сообщений"
      },
      {
       "expr": "commission_fee_processed_success_total",
       "legendFormat": "успешно обработанные комиссии"
      },
      {
       "expr": "commission_fee_processed_error_total",
       "legendFormat": "ошибки при обработке"
      },
      {
       "expr": "commission_fee_processed_duplicate_total",
       "legendFormat": "дублирующиеся сообщения"
      }
     ]
    },
    {
     "title": "Fee Max Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
     "targets": [
      {
       "expr": "commission_fee_processing_duration_seconds_max",
       "legendFormat": "время обработки комиссий"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-transfer-history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23896 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-transfer-history\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23896 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-transfer-history\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-transfer-history\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-transfer-history\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-transfer-history\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23896 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-transfer-history\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Максимальное время обработки",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23904 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{job=\"gpts-transfer-history\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "History events Kafka",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23904 },
     "targets": [
      {
       "expr": "spring_kafka_listener_seconds_count{job=\"gpts-transfer-history\"}",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-sanctions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc вызовы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28454 },
     "targets": [
      {
       "expr": "grpc_server_seconds_count{job=\"gpts-sanctions\"}",
       "legendFormat": "{{rpc_service}} - {{grpc_status_code}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28454 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-sanctions\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-sanctions\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-sanctions\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-sanctions\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28454 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-sanctions\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "grpc_server_seconds_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29086 },
     "targets": [
      {
       "expr": "grpc_server_seconds_max{job=\"gpts-sanctions\"}",
       "legendFormat": "{{rpc_service}} - {{grpc_status_code}}"
      }
     ]
    },
    {
     "title": "Статистика ответов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29086 },
     "targets": [
      {
       "expr": "account_checker_errors_total{job=\"gpts-sanctions\"}",
       "legendFormat": "Ошибки {{exception}}"
      },
      {
       "expr": "account_checker_responses_total",
       "legendFormat": "Успешные ответы {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-limit-fee-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23946 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-limit-fee-service\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23946 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-limit-fee-service\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-limit-fee-service\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23946 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "grpc вызовы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23954 },
     "targets": [
      {
       "expr": "grpc_requests_total{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "{{method}} - {{status}}"
      }
     ]
    },
    {
     "title": "grpc_server_seconds_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23954 },
     "targets": [
      {
       "expr": "grpc_requests_duration_seconds_max{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23954 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23962 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "redis",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23962 },
     "targets": [
      {
       "expr": "lettuce_command_firstresponse_seconds_count{job=\"gpts-limit-fee-service\"}",
       "legendFormat": "{{command}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-transfer-fraud",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc вызовы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23995 },
     "targets": [
      {
       "expr": "grpc_server_seconds_count{application=\"gpts-fraud-service\"}",
       "legendFormat": "{{rpc_service}} - {{grpc_status_code}}"
      }
     ]
    },
    {
     "title": "Соединения к бд",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23995 },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"gpts-fraud-service\"}",
       "legendFormat": "hikaricp_connections_active"
      },
      {
       "expr": "hikaricp_connections_max{application=\"gpts-fraud-service\"}",
       "legendFormat": "hikaricp_connections_max"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"gpts-fraud-service\"}",
       "legendFormat": "hikaricp_connections_pending"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"gpts-fraud-service\"}",
       "legendFormat": "hikaricp_connections_idle"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23995 },
     "targets": [
      {
       "expr": "logback_events_total{application=\"gpts-fraud-service\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "grpc_server_seconds_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24003 },
     "targets": [
      {
       "expr": "grpc_server_seconds_max{application=\"gpts-fraud-service\"}",
       "legendFormat": "{{rpc_service}} - {{grpc_status_code}}"
      }
     ]
    },
    {
     "title": "Общее количество ошибок при проверке мошенничества.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24003 },
     "targets": [
      { "expr": "fraud_check_errors_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Общее количество запросов на проверку мошенничества",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24011 },
     "targets": [
      {
       "expr": "fraud_check_requests_total",
       "legendFormat": "Общее количество запросов на проверку мошенничества"
      },
      { "expr": "fraud_check_decisions_total", "legendFormat": "RESULT: {{decision}}" },
      {
       "expr": "fraud_transactions_total",
       "legendFormat": "Общее количество обработанных транзакций"
      }
     ]
    },
    {
     "title": "Количество срабатываний правил обнаружения мошенничества с разбивкой по типу правила.",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24011 },
     "targets": [
      { "expr": "fraud_rules_triggered_total", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "gpts-client-dash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25683 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-client-dash\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25683 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-client-dash\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-client-dash\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25683 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-client-dash\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25691 },
     "targets": [
      {
       "expr": "increase(http_server_requests_seconds_count{job=\"gpts-client-dash\",uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Запросы feign_client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25691 },
     "targets": [
      {
       "expr": "feign_Client_http_response_code_total{job=\"gpts-client-dash\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{host}} - {{uri}} - {{http_method}} - {{http_status}}"
      }
     ]
    },
    {
     "title": "Максимальное время выполнения запросов feign_client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25691 },
     "targets": [
      {
       "expr": "feign_Client_seconds_max{job=\"gpts-client-dash\"}",
       "legendFormat": "{{host}} - {{uri}} - {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gpts-account-pool-generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Запросы API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25700 },
     "targets": [
      {
       "expr": "http_server_requests_seconds_count{job=\"gpts-account-pool-generator\",uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "Среднее время выполнения запросов",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25700 },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{job=\"gpts-account-pool-generator\",uri!=\"/actuator/prometheus\"}[5m]) / rate(http_server_requests_seconds_count{job=\"gpts-account-pool-generator\",uri!=\"/actuator/prometheus\"}[5m])",
       "legendFormat": "{{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "logstat",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25700 },
     "targets": [
      {
       "expr": "logback_events_total{job=\"gpts-account-pool-generator\"}",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Получение/возврат",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25708 },
     "targets": [
      {
       "expr": "account_pool_accounts_issued_total",
       "legendFormat": "Общее количество выданных счетов из пула."
      },
      {
       "expr": "account_pool_accounts_returned_total",
       "legendFormat": "Общее количество возвращенных счетов в пул"
      },
      {
       "expr": "account_pool_accounts_generated_total",
       "legendFormat": "Общее количество сгенерированных счетов"
      },
      {
       "expr": "account_pool_pools_created_total",
       "legendFormat": " Общее количество созданных пулов"
      }
     ]
    },
    {
     "title": "Генерация/пулы",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25708 },
     "targets": [
      {
       "expr": "account_pool_accounts_generated_total",
       "legendFormat": "Общее количество сгенерированных счетов"
      },
      {
       "expr": "account_pool_pools_created_total",
       "legendFormat": " Общее количество созданных пулов"
      }
     ]
    },
    {
     "title": "Планировщик",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25708 },
     "targets": [
      {
       "expr": "account_pool_checks_executed_total",
       "legendFormat": "Общее количество выполненных проверок пулов"
      },
      {
       "expr": "account_pool_checks_errors_total",
       "legendFormat": "Общее количество ошибок при проверке пулов"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "pg_stat_database_xact_commit / pg_stat_database_xact_rollbac",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24022 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{datname=\"gpts\"}[$__rate_interval])",
       "legendFormat": "commit per second {{datname}}"
      },
      {
       "expr": "rate(pg_stat_database_xact_rollback{datname=\"gpts\"}[$__rate_interval])",
       "legendFormat": "rollback per second {{datname}}"
      }
     ]
    },
    {
     "title": "pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24022 },
     "targets": [
      { "expr": "hikaricp_connections_active", "legendFormat": "__auto" },
      { "expr": "hikaricp_connections_pending", "legendFormat": "__auto" },
      {
       "expr": "hikaricp_connections_timeout_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "inserted + updated + deleted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24030 },
     "targets": [
      {
       "expr": "(rate(pg_stat_database_tup_inserted{datname=\"gpts\"}[$__rate_interval]))\r\n+\r\n(rate(pg_stat_database_tup_updated{datname=\"gpts\"}[$__rate_interval]))\r\n+\r\n(rate(pg_stat_database_tup_deleted{datname=\"gpts\"}[$__rate_interval]))",
       "legendFormat": "TPS ON DB (transactions)"
      }
     ]
    },
    {
     "title": "pg_stat_activity_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24030 },
     "targets": [
      {
       "expr": "pg_stat_activity_count{datname=\"gpts\"}",
       "legendFormat": "{{application_name}} {{backend_type}} - {{datname}} - {{state}} : {{usename}} - {{wait_event}} - {{wait_event_type}}"
      }
     ]
    },
    {
     "title": "сколько строк прочитано (показывает нагрузку на чтение)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24038 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_returned{datname=\"gpts\"}[$__rate_interval])",
       "legendFormat": "READ TPS"
      }
     ]
    },
    {
     "title": "inserted + updated + deleted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24038 },
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{datname=\"gpts\"}[$__rate_interval])",
       "legendFormat": "inserted"
      },
      {
       "expr": "rate(pg_stat_database_tup_updated{datname=\"gpts\"}[$__rate_interval])",
       "legendFormat": "updated"
      },
      {
       "expr": "rate(pg_stat_database_tup_deleted{datname=\"gpts\"}[$__rate_interval])",
       "legendFormat": "deleted"
      }
     ]
    },
    {
     "title": "pg_locks_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24046 },
     "targets": [
      {
       "expr": "pg_locks_count{datname=\"gpts\"}",
       "legendFormat": "{{datname}} - {{mode}}"
      }
     ]
    },
    {
     "title": "pg_stat_activity_waiting",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24046 },
     "targets": [
      {
       "expr": "pg_stat_database_deadlocks{datname=\"gpts\"}",
       "legendFormat": "DEADLOCKS"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "current_offset",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
     "targets": [
      {
       "expr": "kafka_topic_partition_current_offset{topic!=\"__consumer_offsets\"}",
       "legendFormat": "topic {{topic}} part {{partition}}"
      }
     ]
    },
    {
     "title": "kafka_consumer_group_lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag) by (topic,consumergroup)",
       "legendFormat": "LAG topic {{topic}} part {{partition}} - {{consumergroup}}"
      }
     ]
    },
    {
     "title": "current_offset",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
     "targets": [
      {
       "expr": "sum(kafka_topic_partition_current_offset{topic!=\"__consumer_offsets\"}) by (topic)",
       "legendFormat": "topic {{topic}} part {{partition}}"
      }
     ]
    }
   ]
  }
 ]
}